spring.application.name=apiusuarios

# Configuracion del servidor
server.port=8084

# Configuracion de la base de datos
spring.datasource.url=jdbc:mysql://127.0.0.1:3321/usuarios_db?serverTimezone=UTC
spring.datasource.username=myuser
spring.datasource.password=HolaMundo

# Configuracion de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Configuracion Correos
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ptest9349@gmail.com
spring.mail.password=mkho cfvo fbbv laqq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true